"""add_citation_author_property

Revision ID: 596a01c35e4d
Revises: 9af5f0a88329
Create Date: 2023-12-26 18:48:38.721848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596a01c35e4d'
down_revision = '9af5f0a88329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
