"""add_citations_table

Revision ID: 9af5f0a88329
Revises: e8fc9f5f4da4
Create Date: 2023-12-26 18:39:05.166583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af5f0a88329'
down_revision = 'e8fc9f5f4da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citation_description', sa.String(length=2048), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    # ### end Alembic commands ###
